import React from 'react';
import ReactDOM from 'react-dom/client';
import { MdFoodBank } from 'react-icons/md';

const resList = [
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '64387',
      name: '63 By-Lane',
      uuid: '6986c03c-fc94-4ff2-a46f-90165c1aef17',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'gykp6hoxz3wjvqgtgqcn',
      cuisines: ['Pizzas', 'Pastas', 'Salads'],
      tags: [],
      costForTwo: 60000,
      costForTwoString: '₹600 FOR TWO',
      deliveryTime: 45,
      minDeliveryTime: 45,
      maxDeliveryTime: 45,
      slaString: '45 MINS',
      lastMileTravel: 3,
      slugs: {
        restaurant: '63-by-lane-goregaon-east-jog-gor-east',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        '1087, Oshiwara Gokul CHS LTD, Adarsh Nagar, New Link Road, Lotus Petrol Pump, Jogeshwari West, Mumbai - 400102',
      locality: 'Goregaon East',
      parentId: 5465,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 4500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4500,
        message: '',
        title: 'Delivery Charge',
        amount: '4500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7132686~p=1~eid=00000189-026e-cdc6-1aa4-5ca20053014f~srvts=1687962963398',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '3 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '40% OFF',
        subHeader: 'UPTO ₹80',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '64387',
        deliveryTime: 45,
        minDeliveryTime: 45,
        maxDeliveryTime: 45,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.9',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '1584',
      name: 'Sarvodaya Pure Veg',
      uuid: 'b350be43-c57a-4206-9a72-2fb498dd5fec',
      city: '5',
      area: 'Andheri East',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'bxkpzlmxkuwmkffcdy3f',
      cuisines: [
        'North Indian',
        'Chinese',
        'South Indian',
        'Tandoor',
        'Continental',
        'Fast Food',
        'Beverages',
      ],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 49,
      minDeliveryTime: 49,
      maxDeliveryTime: 49,
      slaString: '49 MINS',
      lastMileTravel: 1.2000000476837158,
      slugs: {
        restaurant: 'sarvodaya-pure-veg-andheri-railway-station-andheri-east',
        city: 'mumbai',
      },
      cityState: '5',
      address: 'Vidya Villa 1, 5, Old Nagardas Road, Andheri East',
      locality: 'Andheri Railway Station',
      parentId: 178554,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'special',
            fee: 0,
            message: '',
          },
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'LIGHT',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '20% OFF',
        subHeader: 'UPTO ₹50',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '1584',
        deliveryTime: 49,
        minDeliveryTime: 49,
        maxDeliveryTime: 49,
        lastMileTravel: 1.2000000476837158,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'LIGHT',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.2',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '50951',
      name: 'Mao The Family Restaurant',
      uuid: '64a7e888-253e-4882-9c61-1f825d7046e7',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'mj0u94hmplbutahrrpl0',
      cuisines: ['Indian', 'Chinese'],
      tags: [],
      costForTwo: 30000,
      costForTwoString: '₹300 FOR TWO',
      deliveryTime: 32,
      minDeliveryTime: 32,
      maxDeliveryTime: 32,
      slaString: '32 MINS',
      lastMileTravel: 1,
      slugs: {
        restaurant: 'mao-the-family-restaurant-azad-nagar-andheri-west',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        '63 - 64 Aboobakar Mahal Jai Prakash Road, Next To Azad Nagar Metro Station, Azad Nagar, Mumbai',
      locality: 'Azad Nagar',
      parentId: 230853,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1 kms',
      hasSurge: false,
      sla: {
        restaurantId: '50951',
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '28749',
      name: 'Meraki',
      uuid: '7c5432de-23e5-4b6d-bf26-ff1dc19e2eef',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'lhsxrwuptsc5lzashxgc',
      cuisines: ['Chinese', 'Thai', 'Burmese'],
      tags: [],
      costForTwo: 55000,
      costForTwoString: '₹550 FOR TWO',
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: '39 MINS',
      lastMileTravel: 3,
      slugs: {
        restaurant: 'meraki-lokhandwala-andheri-west',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        '1017, opp oriental college, near lotus petrol pump, adarsh nagar, Andheri West',
      locality: 'Adarsh Nagar',
      parentId: 2356,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 4500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4500,
        message: '',
        title: 'Delivery Charge',
        amount: '4500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=6958375~p=4~eid=00000189-026e-cdc6-1aa4-5ca300530473~srvts=1687962963398',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '3 kms',
      hasSurge: false,
      sla: {
        restaurantId: '28749',
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 3,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.9',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '21216',
      name: "Rishija's Kitchen ( Healthy & Homestyle )",
      uuid: '21df0e5d-cb1e-45db-b649-6790f87f4128',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'c4yz3rhpjkh7y9ytt3dm',
      cuisines: ['Indian', 'Biryani', 'Thalis', 'Healthy Food'],
      tags: [],
      costForTwo: 15000,
      costForTwoString: '₹150 FOR TWO',
      deliveryTime: 27,
      minDeliveryTime: 27,
      maxDeliveryTime: 27,
      slaString: '27 MINS',
      lastMileTravel: 0.30000001192092896,
      slugs: {
        restaurant: 'rishijas-kitchen-vp-road-andheri-west-andheri-west',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        '004,1ST FLOOR, MEHTA HOUSE, BEHIND D.GAYURVEDIC,OPPOSITE RAM MANDIR,METRO PILLER NO 126,J.P ROAD, ANDHERI WEST',
      locality: 'VP Road, Andheri West',
      parentId: 169737,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.3 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '30% OFF',
        subHeader: 'ABOVE ₹700',
        discountTag: 'FLAT DEAL',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '21216',
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        lastMileTravel: 0.30000001192092896,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.8',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '608592',
      name: 'Pizza Hut',
      uuid: 'c8961514-6c5a-4855-977c-72fa7793467d',
      city: '5',
      area: 'Jog Gor West',
      totalRatingsString: '500+ ratings',
      cloudinaryImageId: '2b4f62d606d1b2bfba9ba9e5386fabb7',
      cuisines: ['Pizzas'],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 36,
      minDeliveryTime: 36,
      maxDeliveryTime: 36,
      slaString: '36 MINS',
      lastMileTravel: 1,
      slugs: {
        restaurant: 'pizza-hut-jogeshwari-jog-gor-west',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        'Pizza Hut- Shop no 1 , Ground floor Royal Garden CHS LTD, S.V. Road, Near Farooque High School, Jogeshwari(West), Mumbai- Greater Mumbai-K/W, Greater Mumbai, Maharashtra, 400102',
      locality: 'Jogeshwari',
      parentId: 721,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3600,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3600,
        message: '',
        title: 'Delivery Charge',
        amount: '3600',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '50% OFF',
        subHeader: 'UPTO ₹100',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '608592',
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '3.9',
      totalRatings: 500,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '286577',
      name: 'Smoke House Deli',
      uuid: 'c91ae22d-a69a-4a2f-8912-44b3622eb6f9',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '500+ ratings',
      cloudinaryImageId: 'bmqnqvwvgazlhme8sdko',
      cuisines: ['American', 'Italian', 'European'],
      tags: [],
      costForTwo: 80000,
      costForTwoString: '₹800 FOR TWO',
      deliveryTime: 48,
      minDeliveryTime: 48,
      maxDeliveryTime: 48,
      slaString: '48 MINS',
      lastMileTravel: 3.5,
      slugs: {
        restaurant:
          'smoke-house-deli-savitribai-jyothiba-phule-rd-andheri-west',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        '1311/2, Plot B, Savitribai Jotiba Phule Road, Versova, Andheri West, Mumbai',
      locality: 'Savitribai Jyothiba phule Rd',
      parentId: 874,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 4400,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4400,
        message: '',
        title: 'Delivery Charge',
        amount: '4400',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7204453~p=7~eid=00000189-026e-cdc6-1aa4-5ca400530731~srvts=1687962963398',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '3.5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '₹125 OFF',
        subHeader: 'ABOVE ₹249',
        discountTag: 'FLAT DEAL',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '286577',
        deliveryTime: 48,
        minDeliveryTime: 48,
        maxDeliveryTime: 48,
        lastMileTravel: 3.5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.9',
      totalRatings: 500,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '41288',
      name: 'Cafe Arfa ( Biryani ,Tandoor and more )',
      uuid: '84f8c8cc-d6e0-4fcb-8222-f793f59326ba',
      city: '5',
      area: 'Jogeshwari West',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'c6piwbogisrpl9rin85v',
      cuisines: ['Indian', 'Chinese', 'Tandoor', 'Mughlai'],
      tags: [],
      costForTwo: 10000,
      costForTwoString: '₹100 FOR TWO',
      deliveryTime: 26,
      minDeliveryTime: 26,
      maxDeliveryTime: 26,
      slaString: '26 MINS',
      lastMileTravel: 1.2999999523162842,
      slugs: {
        restaurant: 'cafe-arfa-andheri-west-andheri-west',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        '1 - 3, B Wing, Sajid Tower, SV Road, Amboli, Andheri West, Mumbai',
      locality: 'Sajid Tower',
      parentId: 52371,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.2 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '₹100 OFF',
        subHeader: 'ABOVE ₹999',
        discountTag: 'FLAT DEAL',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '41288',
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        lastMileTravel: 1.2999999523162842,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '528826',
      name: 'Ribbons And Balloons',
      uuid: '585353e9-c8ff-45cb-849e-5661db405657',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: '1265f7c2fbfdcb2936478dede26bfcf5',
      cuisines: ['Bakery', 'Desserts'],
      tags: [],
      costForTwo: 35000,
      costForTwoString: '₹350 FOR TWO',
      deliveryTime: 18,
      minDeliveryTime: 18,
      maxDeliveryTime: 18,
      slaString: '18 MINS',
      lastMileTravel: 0.5,
      slugs: {
        restaurant: 'ribbons-and-balloons-andheri-west-andheri-west-2',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        'SHOP NO. 01, THAKER BLDG, MONGINI CAKE SHOP, S. V. ROAD, NEXT TO POST OFFICE, ANDHERI WEST MUMBAI- 400058, Greater Mumbai Ward-K/W, Greater Mumbai, Maharashtra-400058',
      locality: 'Mongini Cake Shop',
      parentId: 169283,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '20% OFF',
        subHeader: 'UPTO ₹50',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '528826',
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        lastMileTravel: 0.5,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '463032',
      name: 'Maiz Mexican Kitchen',
      uuid: '7712b620-7454-4a5a-8134-2b9c47b1202a',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: '2287f2ce1959e86f3e0bd8cefd412a92',
      cuisines: ['Mexican'],
      tags: [],
      costForTwo: 60000,
      costForTwoString: '₹600 FOR TWO',
      deliveryTime: 40,
      minDeliveryTime: 40,
      maxDeliveryTime: 40,
      slaString: '40 MINS',
      lastMileTravel: 4.599999904632568,
      slugs: {
        restaurant: 'maiz-mexican-kitchen-andheri-west-andheri-west',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        'Shop No. R/43, 1st Floor, RNA Shopping Center, Lokhandwala Complex Market,Main Rd, Next to High Point Restaurant, Andheri West, Mumbai, Maharashtra 400053',
      locality: 'Rna Shopping Center',
      parentId: 11654,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 4500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 4500,
        message: '',
        title: 'Delivery Charge',
        amount: '4500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7026663~p=10~eid=00000189-026e-cdc6-1aa4-5ca500530a30~srvts=1687962963398',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '4.5 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '40% OFF',
        subHeader: 'UPTO ₹80',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '463032',
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        lastMileTravel: 4.599999904632568,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '4.2',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '23702',
      name: "McDonald's",
      uuid: '82919ac9-6bc4-4af7-b692-a438d3d5364d',
      city: '5',
      area: 'Andheri East',
      totalRatingsString: '10000+ ratings',
      cloudinaryImageId: 'ee5f8e06b300efc07c9fe3f4df40dfc4',
      cuisines: ['Burgers', 'Beverages', 'Cafe', 'Desserts'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 39,
      minDeliveryTime: 39,
      maxDeliveryTime: 39,
      slaString: '39 MINS',
      lastMileTravel: 1.600000023841858,
      slugs: {
        restaurant: 'mc-donalds-andheri-east-andheri-east',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        "McDonald's Family Restaurant, Hindu Vabhavan, Sahar Rd, Near Andheri Station, Andheri (E)",
      locality: 'Vaibhav',
      parentId: 630,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3600,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3600,
        message: '',
        title: 'Delivery Charge',
        amount: '3600',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'LIGHT',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1.6 kms',
      hasSurge: false,
      sla: {
        restaurantId: '23702',
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        lastMileTravel: 1.600000023841858,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'LIGHT',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.3',
      totalRatings: 10000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '577072',
      name: 'Merwans Cake Stop',
      uuid: '0283edda-0ff2-4bed-b2cd-444a5e595dc8',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '1000+ ratings',
      cloudinaryImageId: 'y9dej1mezvl3wuxb3txl',
      cuisines: ['Bakery', 'Desserts'],
      tags: [],
      costForTwo: 40000,
      costForTwoString: '₹400 FOR TWO',
      deliveryTime: 22,
      minDeliveryTime: 22,
      maxDeliveryTime: 22,
      slaString: '22 MINS',
      lastMileTravel: 0.6000000238418579,
      slugs: {
        restaurant: 'merwans-cake-stop-andheri-west-andheri-west',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        'SHOP NO-12 AND 13, MADHAV NAGAR S.V ROAD, ANDHERI WEST, Mumbai Suburban, Maharashtra, 400058',
      locality: 'Madhav Nagar',
      parentId: 135373,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.6 kms',
      hasSurge: false,
      sla: {
        restaurantId: '577072',
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        lastMileTravel: 0.6000000238418579,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.5',
      totalRatings: 1000,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '687020',
      name: 'Food Darzee',
      uuid: '6c85a3e7-a0c6-4427-afec-a7b27171ff82',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '100+ ratings',
      cloudinaryImageId: '2f220cdf0a51fda2d3df6595d25b6780',
      cuisines: ['North Indian', 'Asian', 'Continental', 'Keto', 'Desserts'],
      tags: [],
      costForTwo: 50000,
      costForTwoString: '₹500 FOR TWO',
      deliveryTime: 30,
      minDeliveryTime: 30,
      maxDeliveryTime: 30,
      slaString: '30 MINS',
      lastMileTravel: 2.0999999046325684,
      slugs: {
        restaurant: 'food-darzee-andheri-west-andheri-west',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        '"\tSHOP NO. 30, GROUND FLOOR, ANDHERI SHIV SHAKTI CHSL, A WING, NEAR INDIAN OIL NAGAR, , INDIRA NAGAR, ANDHERI WEST, Greater Mumbai, Maharashtra-400053\t "',
      locality: 'Indian Oil Nagar',
      parentId: 394902,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      ribbon: [
        {
          type: 'PROMOTED',
        },
      ],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID:
        'cid=7191096~p=13~eid=00000189-026e-cdc6-1aa4-5ca600530d18~srvts=1687962963398',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '2 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '20% OFF',
        subHeader: 'UPTO ₹50',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '687020',
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        lastMileTravel: 2.0999999046325684,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: true,
      avgRating: '3.9',
      totalRatings: 100,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '538653',
      name: 'Amar Juice Centre - Andheri West',
      uuid: '2f997a86-c29e-49e5-840e-d2cee9962852',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '500+ ratings',
      cloudinaryImageId: 'zhlmnynknwmrtxshpkvk',
      cuisines: ['South Indian', 'Fast Food', 'Chinese'],
      tags: [],
      costForTwo: 25000,
      costForTwoString: '₹250 FOR TWO',
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      slaString: '28 MINS',
      lastMileTravel: 1,
      slugs: {
        restaurant: 'amar-veg-restaurant-andheri-west-andheri-west',
        city: 'mumbai',
      },
      cityState: '5',
      address: 'C-2,Laram centre, m-a. road Ahdgeri west-400058',
      locality: 'M-A Road',
      parentId: 373598,
      unserviceable: false,
      veg: true,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '1 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '10% OFF',
        subHeader: 'UPTO ₹40',
        discountTag: '',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '538653',
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        lastMileTravel: 1,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 500,
      new: false,
    },
    subtype: 'basic',
  },
  {
    type: 'restaurant',
    data: {
      type: 'F',
      id: '230815',
      name: 'Ohhdaily - Healthy & Homely Tiffin Meals',
      uuid: 'a2104ecc-fb70-46b9-b9ee-a2d168b9dc4d',
      city: '5',
      area: 'Andheri West',
      totalRatingsString: '5000+ ratings',
      cloudinaryImageId: 'dx9wkvzqbgnoc3crea2h',
      cuisines: ['Indian', 'Thalis', 'Home Food'],
      tags: [],
      costForTwo: 20000,
      costForTwoString: '₹200 FOR TWO',
      deliveryTime: 29,
      minDeliveryTime: 29,
      maxDeliveryTime: 29,
      slaString: '29 MINS',
      lastMileTravel: 0.30000001192092896,
      slugs: {
        restaurant:
          'ohhdaily--healthy-&-homely-tiffins-andheri-west-andheri-west',
        city: 'mumbai',
      },
      cityState: '5',
      address:
        'Room Number 1, First Floor, Suresh Patil Building, JP Road, Navneeth Colony, Andheri West,Mumbai,Maharashtra-400058',
      locality: 'Navneeth Colony',
      parentId: 151174,
      unserviceable: false,
      veg: false,
      select: false,
      favorite: false,
      tradeCampaignHeaders: [],
      chain: [],
      feeDetails: {
        fees: [
          {
            name: 'distance',
            fee: 3500,
            message: '',
          },
          {
            name: 'time',
            fee: 0,
            message: '',
          },
          {
            name: 'special',
            fee: 0,
            message: '',
          },
        ],
        totalFees: 3500,
        message: '',
        title: 'Delivery Charge',
        amount: '3500',
        icon: '',
      },
      availability: {
        opened: true,
        nextOpenMessage: '',
        nextCloseMessage: '',
      },
      longDistanceEnabled: 0,
      rainMode: 'NONE',
      thirdPartyAddress: false,
      thirdPartyVendor: '',
      adTrackingID: '',
      badges: {
        imageBased: [],
        textBased: [],
        textExtendedBadges: [],
      },
      lastMileTravelString: '0.3 kms',
      hasSurge: false,
      aggregatedDiscountInfoV3: {
        header: '20% OFF',
        subHeader: 'ABOVE ₹600',
        discountTag: 'FLAT DEAL',
        headerTypeV2: 0,
      },
      sla: {
        restaurantId: '230815',
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        lastMileTravel: 0.30000001192092896,
        lastMileDistance: 0,
        serviceability: 'SERVICEABLE',
        rainMode: 'NONE',
        longDistance: 'NOT_LONG_DISTANCE',
        preferentialService: false,
        iconType: 'EMPTY',
      },
      promoted: false,
      avgRating: '4.1',
      totalRatings: 5000,
      new: false,
    },
    subtype: 'basic',
  },
];

const Card = (props) => {
  const { resData } = props;

  const { cloudinaryImageId, name, costForTwo, cuisines } = resData?.data;
  return (
    <div className='card'>
      <div className='card-img-container'>
        <img
          src={`https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/${cloudinaryImageId}`}
        />
        <div className='card-list'>
          <p>{name}</p>
          <p>price: {costForTwo / 100}rs</p>
          <p>cuisines: {cuisines.join(', ')}</p>
        </div>
      </div>
    </div>
  );
};

const Header = () => {
  return (
    <div className='header-container'>
      <div className='logo-container'>
        <MdFoodBank className='logo' />
      </div>
      <ul>
        <li>Home</li>
        <li>About</li>
        <li>Contact</li>
        <li>Cart</li>
      </ul>
    </div>
  );
};

const Body = () => {
  return (
    <div className='body-container'>
      <div className='card-container'>
        {resList.map((restaurant) => (
          <Card key={restaurant.data.id} resData={restaurant} />
        ))}
      </div>
    </div>
  );
};

const App = () => {
  return (
    <div>
      <Header />
      <Body />
    </div>
  );
};

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<App />);
